"""Harness: deterministic test execution via verify.sh."""

from __future__ import annotations

import json
import logging
import subprocess
import uuid
from pathlib import Path
from typing import Any

from automission.docker import build_docker_cmd
from automission.models import HarnessResult, VerificationSurface

logger = logging.getLogger(__name__)


def run_verify_sh(
    workdir: Path,
    script_path: Path,
    docker_image: str = "ghcr.io/codance-ai/automission:latest",
) -> dict[str, Any]:
    """Run verify.sh and return structured gate result.

    Uses a randomized container mount path (instead of /workspace) to detect
    code that hardcodes Docker-specific paths. If generated tests reference
    /workspace, they will fail here — catching portability bugs before the
    mission is marked as passed.
    """
    try:
        # verify.sh must be inside workspace to mount correctly
        try:
            rel_script = (
                script_path.relative_to(workdir)
                if script_path.is_absolute()
                else script_path
            )
        except ValueError:
            return {
                "passed": False,
                "exit_code": -1,
                "stdout": "",
                "stderr": f"verify.sh at {script_path} is outside workspace {workdir}, cannot mount in Docker",
                "json_output": None,
            }
        # Randomized mount path to catch hardcoded /workspace references
        nonce = uuid.uuid4().hex[:8]
        container_workdir = f"/tmp/_verify_{nonce}"
        cmd = build_docker_cmd(
            docker_image,
            # Configure git safe.directory before running verify.sh so git
            # operations work at the non-standard mount path.
            [
                "bash",
                "-c",
                f'git config --global --add safe.directory "{container_workdir}" && bash "{rel_script}"',
            ],
            workdir=workdir,
            container_workdir=container_workdir,
        )
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120, encoding="utf-8"
        )
        stdout = result.stdout
        stderr = result.stderr
        passed = result.returncode == 0

        # Try to parse JSON from stdout
        json_output = None
        try:
            json_output = json.loads(stdout.strip())
        except (json.JSONDecodeError, ValueError):
            pass

        return {
            "passed": passed,
            "exit_code": result.returncode,
            "stdout": stdout,
            "stderr": stderr,
            "json_output": json_output,
        }
    except subprocess.TimeoutExpired:
        return {
            "passed": False,
            "exit_code": -1,
            "stdout": "",
            "stderr": "verify.sh timed out after 120s",
            "json_output": None,
        }
    except FileNotFoundError:
        return {
            "passed": False,
            "exit_code": -1,
            "stdout": "",
            "stderr": f"Script not found: {script_path}",
            "json_output": None,
        }


class Harness:
    """Deterministic test execution — runs verify.sh, returns structured result."""

    def __init__(self, docker_image: str = "ghcr.io/codance-ai/automission:latest"):
        self.docker_image = docker_image

    def run(self, workdir: Path, verify_sh: Path | None) -> HarnessResult:
        """Run verify.sh and return deterministic result."""
        if verify_sh and verify_sh.exists():
            gate = run_verify_sh(workdir, verify_sh, docker_image=self.docker_image)
            return HarnessResult(
                passed=gate["passed"],
                exit_code=gate["exit_code"],
                stdout=gate["stdout"],
                stderr=gate["stderr"],
                json_output=gate.get("json_output"),
            )
        return HarnessResult(passed=False, exit_code=-1, stderr="No verify.sh")


def render_verify_sh(surface: VerificationSurface) -> str:
    """Generate verify.sh content from verification surface metadata."""
    parts = [surface.runner]
    if surface.targets:
        parts.extend(surface.targets)
    if surface.options:
        parts.append(surface.options)
    command = " ".join(parts)
    return (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        'cd "$(dirname "$0")"\n'
        "\n"
        "# Auto-generated by automission harness\n"
        f"{command}\n"
    )
